import os

EVENTHUB_CONN = os.getenv("EVENTHUB_CONN")
EVENTHUB_NAME = os.getenv("EVENTHUB_NAME")
CONSUMER_GROUP = os.getenv("CONSUMER_GROUP")

STORAGE_CONN = os.getenv("STORAGE_CONN")
CHECKPOINT_CONTAINER = os.getenv("CHECKPOINT_CONTAINER")

BASE_URL = os.getenv("GRIDDB_WEBURL")
GRIDDB_AUTH = os.getenv("GRIDDB_AUTH")
ROWDATA_CONTAINER_NAME = os.getenv("ROWDATA_CONTAINER_NAME")
EVENT_CONTAINER_NAME = os.getenv("EVENT_CONTAINER_NAME")